### ISSUE TITLE
Custom angular widget by extending esri widget

### ISSUE THREAD

**Issue by gamreddy** [andygup/angular-plus-arcgis-javascript-ds2020#66]
Hi Andy,

Is it possible to create custom widgets in Angular by extending arcgis api for javascript's widget like BasemapGallery or Sketch?

Thanks!

**Comment by andygup** [comment]
Yes, you can extent custom widgets in the ArcGIS API for JavaScript. This functionality is separate from the Angular framework. I recommend building and testing your custom widget outside of Angular first to speed up your development process.

**Comment by gamreddy** [comment]
Do we have to do the custom widget in DOJO and then bring it into Angular app? I am trying to follow https://developers.arcgis.com/javascript/latest/sample-code/widgets-custom-widget/index.html.

**Comment by andygup** [comment]
Closing...let me know if you have additional questions.
